name: 'Tangle'
on:
  - workflow_dispatch
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs-nox
    - name: Versions
      run: |
        emacs --version
        emacs --batch -f org-version
        python3 --version
    - name: Clean
      run: |
        rm keyboards/{*,*/*,*/*/*}/keymaps/manna-harbour_miryoku/*
        rm layouts/community/*/manna-harbour_miryoku/*
        rm users/manna-harbour_miryoku/*
        git checkout users/manna-harbour_miryoku/{miryoku,README}.org
        git status -s
    - name: Tangle
      run: |
        emacs --batch -eval '(setq org-confirm-babel-evaluate nil)' -eval "(require 'ob-python)" -eval '(setq org-babel-python-command "python3")' users/manna-harbour_miryoku/miryoku.org -f org-babel-tangle
    - name: Test
      run: |
        git status -s
        git diff --exit-code
